-- 临时补充市场详情表字段注释。
-- MySQL 修改字段注释需要通过 MODIFY COLUMN 重述字段定义；本脚本不调整字段类型、默认值、索引或数据。

ALTER TABLE `fund_nav_history`
    MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '基金净值历史ID',
    MODIFY COLUMN `fund_code` VARCHAR(50) NOT NULL COMMENT '基金代码',
    MODIFY COLUMN `nav_date` DATE NOT NULL COMMENT '净值日期',
    MODIFY COLUMN `unit_nav` DECIMAL(18,6) DEFAULT NULL COMMENT '单位净值',
    MODIFY COLUMN `accumulated_nav` DECIMAL(18,6) DEFAULT NULL COMMENT '累计净值',
    MODIFY COLUMN `daily_growth_rate` DECIMAL(12,4) DEFAULT NULL COMMENT '日增长率，单位为百分点',
    MODIFY COLUMN `source_as_of` DATETIME DEFAULT NULL COMMENT '数据源数据时间',
    MODIFY COLUMN `fetched_at` DATETIME NOT NULL COMMENT '数据获取时间',
    MODIFY COLUMN `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE `stock_price_bar`
    MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '股票价格时间序列ID',
    MODIFY COLUMN `stock_code` VARCHAR(50) NOT NULL COMMENT '股票代码',
    MODIFY COLUMN `market` VARCHAR(20) NOT NULL COMMENT '业务市场：A_SHARE/US_STOCK',
    MODIFY COLUMN `granularity` VARCHAR(20) NOT NULL COMMENT '时间粒度',
    MODIFY COLUMN `bar_time` DATETIME NOT NULL COMMENT '行情周期时间',
    MODIFY COLUMN `open_price` DECIMAL(20,6) DEFAULT NULL COMMENT '开盘价',
    MODIFY COLUMN `high_price` DECIMAL(20,6) DEFAULT NULL COMMENT '最高价',
    MODIFY COLUMN `low_price` DECIMAL(20,6) DEFAULT NULL COMMENT '最低价',
    MODIFY COLUMN `close_price` DECIMAL(20,6) DEFAULT NULL COMMENT '收盘价',
    MODIFY COLUMN `volume` DECIMAL(28,6) DEFAULT NULL COMMENT '成交量',
    MODIFY COLUMN `currency` VARCHAR(3) DEFAULT NULL COMMENT '价格币种',
    MODIFY COLUMN `source_as_of` DATETIME DEFAULT NULL COMMENT '数据源数据时间',
    MODIFY COLUMN `fetched_at` DATETIME NOT NULL COMMENT '数据获取时间',
    MODIFY COLUMN `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE `stock_company_profile`
    MODIFY COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '股票公司资料ID',
    MODIFY COLUMN `stock_code` VARCHAR(50) NOT NULL COMMENT '股票代码',
    MODIFY COLUMN `market` VARCHAR(20) NOT NULL COMMENT '业务市场：A_SHARE/US_STOCK',
    MODIFY COLUMN `company_name` VARCHAR(200) DEFAULT NULL COMMENT '公司名称',
    MODIFY COLUMN `industry` VARCHAR(200) DEFAULT NULL COMMENT '所属行业',
    MODIFY COLUMN `business_summary` TEXT DEFAULT NULL COMMENT '主营业务摘要',
    MODIFY COLUMN `company_profile` TEXT DEFAULT NULL COMMENT '公司简介',
    MODIFY COLUMN `website` VARCHAR(500) DEFAULT NULL COMMENT '公司网站',
    MODIFY COLUMN `source_as_of` DATETIME DEFAULT NULL COMMENT '数据源数据时间',
    MODIFY COLUMN `fetched_at` DATETIME NOT NULL COMMENT '数据获取时间',
    MODIFY COLUMN `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
